export const TRAINING_CAMERA_CONSTANTS = {
  WIDTH: 640,
  HEIGHT: 480,
  FPS: 5,
  MAX_FRAMES_WITHOUT_DETECTION: 3,
  TAKE_PHOTO_INTERVAL: 300,
  MAX_TAKE_PHOTO_TIME_DELTA: 10,
  TAKE_PHOTO_DELAY: 3,
  PAINT_COLOR: 'red',
  PAINT_STROKE_WIDTH: 3,
};

export const CAMERA_CONSTANTS = {
  FPS: 15,
  MAX_FRAMES_WITHOUT_DETECTION: 5,
};
